#!/bin/bash
# Instructions for setting up Gmail filters

echo "📧 GMAIL FILTER SETUP INSTRUCTIONS"
echo "==================================="
echo ""
echo "Open Gmail and create these filters:"
echo ""
echo "1. Internship Opportunities Filter:"
echo "   - From: jobs@linkedin.com OR alerts@indeed.com OR jobs@wayup.com OR opportunities@jopwell.com"
echo "   - Action: Label 'Internships/Opportunities', Skip Inbox"
echo ""
echo "2. Scholarships Filter:"
echo "   - From: scholarships@hsf.net OR scholarships@shpe.org OR alpfa.org"
echo "   - Action: Label 'Scholarships/New', Skip Inbox"
echo ""
echo "3. Applied Jobs Filter:"
echo "   - Subject: 'Application Received' OR 'Application Submitted'"
echo "   - Action: Label 'Internships/Applied'"
echo ""
echo "Manual steps:"
echo "1. Go to Gmail → Settings → Filters and Blocked Addresses"
echo "2. Click 'Create new filter'"
echo "3. Add the FROM addresses above"
echo "4. Apply labels and skip inbox"
echo ""
